### ISSUE TITLE
Bottom and right 10 pixels of window are not clickable

### ISSUE THREAD

**Issue by robxnano** [FedoraQt/QAdwaitaDecorations#48] opened 2023-12-24 22:20 UTC
OS: Fedora Workstation 39

I found this when trying to increase the size of the window shadows. An area equal to `ceShadowsWidth` is not clickable on the bottom and right edges of the window. I think this might be an upstream Qt bug but I just wanted to check whether there's anything that can be done to fix it here.

**Comment by grulja** [comment] 2023-12-27 11:03
Do you mean the area inside an app or outside where you can drag the window to resize it?

**Comment by robxnano** [comment] 2023-12-27 23:02
The former. It's not obvious in most applications but the buttons on the bottom toolbar in KWrite show the problem. Only the top half is clickable.

**Comment by grulja** [comment] 2024-01-02 07:27
Thanks for an example, I can reproduce now. It's probably a bug in `QAdwaitaDecorations` as I cannot reproduce it with `bradient`. Can you confirm it works with `QT_WAYLAND_DECORATION=bradient kwrite`?

**Comment by robxnano** [comment] 2024-01-03 20:07
Yes it does work, but I think that's only because bradient doesn't have any shadows outside the normal window border. I made a potential fix over at https://codereview.qt-project.org/c/qt/qtwayland/+/527586, perhaps you could take a look and see if it looks right.

**Comment by grulja** [comment] 2024-01-04 10:17
> Yes it does work, but I think that's only because bradient doesn't have any shadows outside the normal window border. I made a potential fix over at https://codereview.qt-project.org/c/qt/qtwayland/+/527586, perhaps you could take a look and see if it looks right.

Looks good to me. I also tested it and it works. Thanks.

**Comment by grulja** [comment] 2024-01-04 10:25
I'm going to close this issue here and backport your fix to Qt in Fedora.

**Closed by grulja** 2024-01-04 10:25 UTC
