### ISSUE TITLE
QMessageBox text cut off

### ISSUE THREAD

**Issue by johnthacker** [FedoraQt/QAdwaitaDecorations#66] opened 2024-05-10 15:11 UTC
With QT_WAYLAND_DECORATION set to adwaita, QMessageBox text is cut off. Example from running `wireshark`:

![adwaita decorations](https://github.com/FedoraQt/QAdwaitaDecorations/assets/17785741/d753a45b-002f-403b-9e13-3902b7f60e7b)

With `QT_WAYLAND_DECORATION=bradient wireshark`:

![bradient decorations](https://github.com/FedoraQt/QAdwaitaDecorations/assets/17785741/e7aff1d7-2696-4ece-a0ab-e1cfe47f5b73)

**Comment by johnthacker** [comment] 2024-05-10 15:12
This is on a Fedora 40 system, using the official Fedora wireshark package `wireshark-4.2.4-2.fc40.x86_64`

**Comment by johnthacker** [comment] 2024-05-10 15:14
![quit](https://github.com/FedoraQt/QAdwaitaDecorations/assets/17785741/a5437199-4bf7-4f77-8804-d2b9eefba7eb)

It's impossible to resize the dialog.

**Comment by grulja** [comment] 2024-05-13 06:22
Interesting, I don't think decorations can have any impact on dialog size, it's basically just implemented painted operation. I tried with `kate` and didn't reproduce, not sure how I can invoke this dialog in `wireshark` without trying to capture something.

**Comment by johnthacker** [comment] 2024-05-13 11:14
Opening an existing file, adding a comment (e.g., Edit->Packet Comments->Add New Comment), and trying to close without saving:
![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/17785741/414659d9-89df-41ef-b287-9e264a800049)

Opening Wireshark with a Lua script with a syntax error. (Garbage can be placed in a plugin directory, but `wireshark -X lua_script:not_a_lua_script.txt` will work):

`wireshark -X lua_script:WiresharkConfigVersion.cmake`

![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/17785741/e89e701a-967c-4496-8289-c815915645ae)

`QT_WAYLAND_DECORATION=bradient wireshark -X lua_script:WiresharkConfigVersion.cmake`:

![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/17785741/f4b6e75b-d490-46ce-b08b-69694ab73324)

You can see that the buttons are smaller as well. The titlebar is taller, and there's space for the drop shadows. Perhaps the auto calculations for how much space to leave for the text is not taking the changed decorations into account.

**Comment by johnthacker** [comment] 2024-05-13 11:18
Open a file, right click on a protocol name in the protocol tree and select "Wiki Protocol Page":

![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/17785741/420fcc1b-30d7-4ce9-a11d-b0c2a331195b)

With `QT_WAYLAND_DECORATION=bradient`:
![image](https://github.com/FedoraQt/QAdwaitaDecorations/assets/17785741/8ccb4cbd-48f1-4f1f-9aa1-b1c96a202f30)

**Comment by grulja** [comment] 2024-05-13 11:27
I still cannot reproduce it, at least when I try this under Weston. I will try later in GNOME.

My test workflow:
1) Run `weston`
2) Open the terminal there and run `export XDG_CURRENT_DESKTOP=GNOME`
3) Run `wireshark`

**Comment by grulja** [comment] 2024-05-13 11:49
I can reproduce now with nested Mutter. I didn't know it can be run this way. I will look into this.

**Comment by grulja** [comment] 2024-05-13 12:04
It's a bug in Qt. I will try to fix it there.

**Comment by grulja** [comment] 2024-05-13 13:05
Closing it here.

Proposed upstream fix: https://codereview.qt-project.org/c/qt/qtwayland/+/560854

**Closed by grulja** 2024-05-13 13:05 UTC

**Comment by grulja** [comment] 2024-05-14 14:09
It turns out the issue is not in Qt, but it's a combination of Wireshark setting all windows as maximized initially and QAdwaitaDecorations reporting wrong margins, since the window has `maximized` state, even though it's not maximized as it's just a QMessageBox or whatever, but I don't know how to fix it or workaround it.

**Comment by johnthacker** [comment] 2024-05-14 14:29
The QMessageBox has maximized state? That seems unlikely since it's happening in cases where a default QMessageBox is being created on the stack or the QMessageBox static functions are being called, but I'm happy to change the Wireshark code if the problem is somehow there.

Certainly if I call
`qWarning() << "maximized" << msg_dialog.isMaximized() << msg_dialog.isFullScreen();`

immediately before
`msg_dialog.exec();`

it prints false to the console for both.

**Comment by johnthacker** [comment] 2024-05-14 14:44
The Wiki page example that is cut off is from calling the static function:

```c++
    int ret = QMessageBox::question(this, mainApp->windowTitleString(tr("Wiki Page for %1").arg(proto_abbrev)),
                                    tr("<p>The Wireshark Wiki is maintained by the community.</p>"     
                                    "<p>The page you are about to load might be wonderful, "           
                                    "incomplete, wrong, or nonexistent.</p>"
                                    "<p>Proceed to the wiki?</p>"),
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::Yes); 
```

Which seems unlikely to set any of the visibility or flags.

**Comment by grulja** [comment] 2024-05-14 14:48
You are right, I didn't realize the maximized state is for the main window and not for the QMessageBox. Ignore what I wrote and I might actually be right with the Qt issue.

**Comment by grulja** [comment] 2024-05-15 13:08
Fixed in Mutter: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3755

**Comment by johnthacker** [comment] 2024-06-03 12:46
Just wanted to confirm that the fix in Mutter works for me.
